# Site settings
title: Leslie Restrepo
email: leslierestrepo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Full Stack Rails developer en formacion, Ingeniera de sistemas.
  Jugadora de voleiplaya y aficionada a la fotografia.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
facebook_username: leslierestrepo
instagram_username: lesrpo
twitter_username: lesrpo
github_username:  lesrpo
mobile: +971 50 5890320
# Build settings
markdown: kramdown
